variables:
- name: 'BuildTag'
  value: $[counter(format('{0}/',variables['Build.SourceBranch']), 0)]

name: $(SourceBranchName)_$(Date:yyyyMMdd).$(BuildTag)

trigger:
  paths:
    include:
      - 510-000/53008BAIL/*
      - 510-000/53008BAIL/Gabarits/*
      - 510-000/53008BAIL/pdf/*

steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder: .\510-000
    Contents: 53008BAIL\**
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
